{
 "title": "Speedtest",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Speedtest.net",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stne_download", "legendFormat": "Download {{server}}" },
    { "expr": "stne_upload", "legendFormat": "Upload {{server}}" }
   ]
  },
  {
   "title": "Speedtest.net Bytes transfered",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "MiB" }
   ],
   "targets": [
    { "expr": "stne_received/1048576", "legendFormat": "Received megabytes {{server}}" },
    { "expr": "stne_sent/1048576", "legendFormat": "Sent megabytes {{server}}" }
   ]
  },
  {
   "title": "Blackbox exporter icmp",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\"}*1000\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}